### ISSUE TITLE
Web interface will not accept input

### ISSUE THREAD

**Issue by Flabort** [Noeda/dfterm3#11]
When trying to connect to a server (I was trying Putnam's, but that seems to have been taken down for now), after signing in, I cannot input anything or do anything. Chat seems to work, as I can input comments.
I cannot select "Continue", "start", or "generate new world", or anything of the sort, let alone play in a fort.

Trying multiple browsers, I have the same problem on all of them. However, on all tests no-one else appeared to be on the server - this may be related and needs more testing. If I could maybe log onto a server while someone else is confirmed on, and test the chat, that would yield more information.

Another forum member has brought this up (Vyro), though he has since apparently succeeded. 

If this is related to open or closed ports, then perhaps some more information on opening ports would be useful. If this is something to do with hardware, that would also be useful. If it has to do with the settings on my browser (default settings, most recent version of firefox) that concern "websockets", information on setting this would be useful, too. If fact, since the problem is probably on my end, any information on solving this problem would be appreciated.

**Comment by Noeda** [comment]
I've seen this report before and I suspect it's caused by the same problem as the connection problems (issue #4). 0.3 will have a slightly different model of handling Dwarf Fortress connections and then we'll test if this particular issue still persists.

**Comment by Flabort** [comment]
I suspect that it may be related, but not the same problem - possibly this issue is one of the triggers that can cause #4, and open more windows. However, solving that seems unlikely to solve this, and solving this seems unlikely to entirely solve that. We'll see when V0.3 is released.

**Comment by Noeda** [comment]
Is there a situation where you can see the game moving but input does not work? For example, if you have FPS display enabled in Dwarf Fortress, can you see the FPS fluctuate but input still does not work?

**Comment by Noeda** [comment]
Closed for 0.3 unless this issue is seen again.
