### ISSUE TITLE
Plugin fails to load on WinXP

### ISSUE THREAD

**Issue by slowriot** [Noeda/dfterm3#20]
Launching dwarf fortress with the dfterm3 dfhack plugin on windows xp sp2 immediately pops up a dialogue box saying:
`The procedure entry point QueryFullProcessImageNameW could not be located in the dynamic link library KERNEL32.dll`
followed by
`Can't load plugin D:\df\df_34_11_win\hack\plugins\dfterm3.plug.dll`
in the dfhack console.  The rest runs normally, but obviously without dfterm.

Apparently QueryFullProcessImageNameW is only available in Vista upwards.

**Comment by Noeda** [comment]
It was known to me that the plugin does not work on Windows XP, however, I guess it's good we now have an actual issue on it.

**Comment by Noeda** [comment]
I won't fix this because it appears that XP is going to expire. I will accept a patch to the plugin though, if someone wants this.
