### ISSUE TITLE
Can´t register a dwarf fortress game

### ISSUE THREAD

**Issue by Tadsching** [Noeda/dfterm3#22]
Hello, 

when I want to register a new game in the web interface, there appears a message that contains following:
"Happstack 7.3.0

Your file is not found
To try again is useless
It is just not here"

All ports are open, and the game ist found.

What can I do?

**Comment by Noeda** [comment]
What kind of URL exactly are you using in the web interface? This could mean that you are running the dfterm3 binary away from the web-interface directory (so it can't find the files) or the URL itself is wrong.

That message is the 404 message of dfterm3.

**Comment by Tadsching** [comment]
I use the URL 127.0.0.1:8081/admin. Is it wrong?

**Comment by Perky87** [comment]
Hello, i have the same Problem, i started Dwarf Fortress from the LNP.
Then, i see the game and when i click "Add" i get a Happstack 7.3.0

Then, i started the raw Version of Dwarf Fortress, only with the Download from your topic for DFHack but its the same error.

I have Windows 7 64bit and all Ports are open.

**Comment by Noeda** [comment]
Do you know if you are running the 0.3 version of dfterm3 or the development 0.4 version?

**Comment by Tadsching** [comment]
Version 0.3

**Comment by Perky87** [comment]
v0.3 too

**Comment by Noeda** [comment]
It's weird. I cannot reproduce this bug (on Linux). I know the development version is not working properly right now but 0.3 should. I have to investigate this by trying the LNP version on Windows.

**Comment by Noeda** [comment]
I wrote it here before but redacted it because I thought I was wrong but did you try
http://127.0.0.1:8081/admin/
(note the final slash)

**Comment by Tadsching** [comment]
Oh my dear... Lol...thank you. It works...! :)

**Comment by Noeda** [comment]
Yeah, I know it's stupid but that's how it works. Glad you got it to work. Closing up!
