### ISSUE TITLE
Text glitch/ [Request] Tileset support

### ISSUE THREAD

**Issue by Zachwak840** [Noeda/dfterm3#32]
1. Text dose not appear in chrome V.35.0.1916.114 m.
2. [Request] Tileset support, i love the game but hate the graphics.

**Comment by Noeda** [comment]
Tilesets may be coming. No promises on ETA.

**Comment by lethosor** [comment]
Can you provide a screenshot of point 1?

**Comment by Zachwak840** [comment]
![screenshot 2014-06-08 14 19 41](https://cloud.githubusercontent.com/assets/7826359/3211928/8d69058c-ef39-11e3-99ca-fd3d97a6d13c.png

Here all text looks like this or simply dosnt appear.

**Comment by lethosor** [comment]
Hmm, I remember seeing something like that with 0.1 ([here](http://www.bay12forums.com/smf/index.php?topic=129995.msg4509865#msg4509865)). You're using the current version of Dfterm3, right? (0.3.1)
Edit: Disabling Truetype and graphics might work (try Truetype first).

**Comment by Zachwak840** [comment]
![screenshot 2014-06-08 14 34 56](https://cloud.githubusercontent.com/assets/7826359/3211958/a2d847e6-ef3b-11e3-8b83-4b87a5bcf549.png)

Yes running Dfterm3  0.3.1

**Comment by lethosor** [comment]
Did you try disabling Truetype?

**Comment by Zachwak840** [comment]
![screenshot 2014-06-08 14 40 31](https://cloud.githubusercontent.com/assets/7826359/3211971/69f007ec-ef3c-11e3-98d9-eb9e812def1f.png)

Thank you 

disabling true type did fix it
