### ISSUE TITLE
Dfterm3 occasionally loses connection to Dfhack Dfterm3 plugin

### ISSUE THREAD

**Issue by Noeda** [Noeda/dfterm3#4]
Putnam wrote in the Bay12 forums:

"Okay, so sometimes DFTerm3 loses contact with DF. And then it opens a new copy without checking for the old one first."

This needs to be investigated and fixed.

**Comment by Putnam3145** [comment]
Yeah, I'm getting a good 16 superfluous copies of DF open an hour due to this.

**Comment by lethosor** [comment]
I'm curious as to what's causing DF to re-open - it's most likely the `dfterm3` process noticing the absence of the dfhack plugin, but I don't understand why the plugin would fail.

**Comment by Noeda** [comment]
I know one reason why the connection might drop. I had a naive way of handling data sending that would disconnect at first sign of congestion. I've fixed it to the plugin repository but I haven't tested if that stops the disconnects.

As for why too many Dwarf Fortresses get opened; is has to do with the current way how Dwarf Fortresses are detected. Dfterm3 periodically polls ports between 48000-48100 so that it takes at most 20 to check any particular port. If there is a Dwarf Fortress running and it has not checked the port yet and someone clicks the game from the web interface, it starts a new Dwarf Fortress because it thinks there is none running. Fixing this should be straightforward (there is a way to 99% reliably check that there is a Dwarf Fortress running from some directory) but might need some work.

I think I mentioned this on the forums but it will take some time before I can start fixing anything. I'm currently travelling and once I settle down, I'll start fixing things.

By the way, there is no code in Dfterm3 to automatically start a Dwarf Fortress. It always requires someone to press the game link in the web interface. If it really starts a Dwarf Fortress all by itself, well, I'm puzzled.

**Comment by Noeda** [comment]
I'm closing the issue because the changes in the plugin might have fixed this. I could not properly test this so let us reopen this issue if this did not help.

The plugin should not lose connection that easily now but it is still not fully guaranteed you are not going to get extra Dwarf Fortress sessions but if the fix works, it should be quite unlikely for that to happen.

**Comment by Noeda** [comment]
I just managed to create more than one Dwarf Fortress through the interface. I guess this one is not solved quite so easily.

**Comment by Noeda** [comment]
Commit Noeda/dfterm3-plugin@bbc47969a5ed1d5dee66d7f2d7abbecfbbbc555e in the Dfhack Dfterm3 plugin may fix this but it should be tested.

**Comment by Noeda** [comment]
No one has reported problems with 0.3 so I'm assuming this is fixed. Re-open if this is not the case.
