### ISSUE TITLE
Web interface doesn't check for websocket port

### ISSUE THREAD

**Issue by lethosor** [Noeda/dfterm3#8]
If the websocket port is changed (with `--websocket`), the JS in playing.html still assumes the port is 8000.
A possible solution could be to generate a JavaScript/JSON file with Haskell containing the websocket port, e.g.:

``` javascript
dfterm3_ports = {
  'websocket': 8000
}
```

which could be included in playing.html before connecting to the websocket server.

**Comment by Noeda** [comment]
Fixed in 25f31a305ba46fd1301c5255d9ea077dc6cc6933.

If more than one WebSocket port is specified, the client side code shall select a port at random.
